
import { Code, Book, Star } from "lucide-react";

const Footer = () => {
  return (
    <footer className="bg-muted/30 border-t mt-12">
      <div className="container mx-auto px-4 py-8">
        <div className="grid gap-8 md:grid-cols-3">
          <div>
            <h3 className="font-bold text-lg mb-4 bg-gradient-to-r from-orange-500 to-red-500 bg-clip-text text-transparent">
              SatireBot News
            </h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              An AI-powered satirical news platform that creates humorous takes on real current events. 
              All content is generated by artificial intelligence for entertainment purposes only.
            </p>
          </div>
          
          <div>
            <h4 className="font-semibold mb-4">Important Information</h4>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li className="flex items-center gap-2">
                <Star className="h-3 w-3" />
                All content is AI-generated satire
              </li>
              <li className="flex items-center gap-2">
                <Book className="h-3 w-3" />
                Based on real news sources
              </li>
              <li className="flex items-center gap-2">
                <Code className="h-3 w-3" />
                Updated automatically every 2-4 hours
              </li>
            </ul>
          </div>
          
          <div>
            <h4 className="font-semibold mb-4">Categories</h4>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li><a href="#" className="hover:text-primary transition-colors">Politics</a></li>
              <li><a href="#" className="hover:text-primary transition-colors">Technology</a></li>
              <li><a href="#" className="hover:text-primary transition-colors">Sports</a></li>
              <li><a href="#" className="hover:text-primary transition-colors">Entertainment</a></li>
              <li><a href="#" className="hover:text-primary transition-colors">Local News</a></li>
            </ul>
          </div>
        </div>
        
        <div className="border-t mt-8 pt-6 text-center">
          <p className="text-sm text-muted-foreground">
            © 2024 SatireBot News. AI-Generated Satirical Content. Not Real News.
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
